---
title: "chemical data"
output: html_document
date: "2023-03-17"
---

```{r setup, include=FALSE}
packages_used <- c("tidyverse", "ggplot2", "here", "stringr" , "sommer","lme4","metan", "rrBLUP")
ip <- installed.packages()
all_packages_installed <- TRUE
for (package in packages_used){
  if (!(package %in% ip[,"Package"])){
    print(paste("Please install package", package))
    all_packages_installed <- FALSE
  }
}#END packages_used
if (!all_packages_installed) stop("Need to install packages")
```

```{r Use here package}
require(here)
here::i_am("analysis/PYT_Chemical_Analysis.Rmd")
library(tidyverse)
```

```{r read in the data}
Umu_oto_Amyl_20<- read.csv(here::here("data/PYT_chemical_data", "Otobi_umudike_2020.csv"), head=T)
head(Umu_oto_Amyl_20)
summary(Umu_oto_Amyl_20)

Oto_21 <- read.csv(here::here("data/PYT_chemical_data", "Otobi_garri_amylose_2021.csv"), head=T)
str(Oto_21)
summary(Oto_21)

Oto_22 <- read.csv(here::here("data/PYT_chemical_data", "Otobi_garri_amylose_2022.csv"), head=T)
head(Oto_22)
summary(Oto_22)

Umu_21 <- read.csv(here::here("data/PYT_chemical_data", "Umudike_garri_pyt_2021.csv"), head=T)

summary(Umu_21)

Umu_22 <- read.csv(here::here("data/PYT_chemical_data", "Umudike_garri_amylose_2022.csv"), head=T)
head(Umu_22)
summary(Umu_22)
```

```{r work on Umu_oto data to be same form with the rest of the data}
Umu_oto_Amyl_20 <- Umu_oto_Amyl_20 %>% relocate(Year, Location) # change the order of the year and the location

#Umu_oto_Amyl_20<- Umu_oto_Amyl_20 %>% 
     # dplyr::rename(Amylose= AMYLOSE) 

```


```{r binding the All the data}
All_amyl<- rbind(Umu_oto_Amyl_20,Oto_21,Oto_22,Umu_21,Umu_22)
dim(All_amyl)
str(All_amyl)
All_amyl$Year<-as.factor(All_amyl$Year)
All_amyl$Location<-as.factor(All_amyl$Location)
All_amyl$Genotype<-as.factor(All_amyl$Genotype)

All_amyl_cf <- All_amyl %>% arrange(Location) # sort the data according to Location


```

```{r}
write.csv(x = All_amyl_cf, file = "data/PYT_chemical_data/All_years_chem.csv")

All_chem <- read.csv(here::here("data/PYT_chemical_data/All_years_chem.csv"), header=TRUE)
str(All_chem)
head(All_chem)
All_chem<- All_chem %>%dplyr::rename(year=Year, location=)
    
All_chem=All_chem[-1]

All_chem$year <-as.factor(All_chem$year)
All_chem$location<-as.factor(All_chem$location)
All_chem$Genotype<-as.factor(All_chem$Genotype)
str(All_chem)
summary(All_chem)
```

```{r looking for genotypes in snp_dosage that are in chem_func}

geno = which(chem_func$Genotype %in% rownames(snps_dosage) ) # identify the row number/genotype name those genotypes from pheno to snps
dim(geno)
```



